
version: '3.1'
# Define services
services:
  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: ./gogorillarest # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    image: erasmolpa/goredis
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on:
      - redis # This service depends on redis. Start that first.
    environment:
      REDIS_URL: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  
  # Redis Service
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD} # Use a public Redis image to build the redis service
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - backend
networks:
  backend: